Add Logging to ShareazaDownloadParserTest for Debugging Header Issues
sepinf-inc/IPED pull request #2339
Opened 2024-10-15 21:12 UTC by marcus6n

This pull request adds logging to the ShareazaDownloadParserTest to help debug issues related to the file header. The changes include:

- Logging the first three bytes of the file in hexadecimal format to verify the file header.
- Resetting the input stream after reading the header to ensure the parser reads the file from the beginning.

2025-02-18 20:11 UTC, lfcnassif requested changes
Thanks @marcus6n! Please also test for key-values stored in the metadata object after the parser.parse(...) call.

2025-02-18 20:13 UTC, lfcnassif requested changes
Extending the TiffPageParserTest doesn't seem correct, please extend BaseItemSearchContext.

2025-02-18 20:17 UTC, marcus6n commented
All right, I'll adjust it properly.

2025-02-19 18:19 UTC, marcus6n commented
@lfcnassif I've made the changes you requested and added some more metadata tests.

2025-03-10 19:19 UTC, marcus6n commented
Waiting your review @lfcnassif .

2025-04-08 19:21 UTC, lfcnassif approved these changes
Thanks @marcus6n!

2025-04-08 19:27 UTC, merged